name: my_package
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  freezed_annotation:


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner:
  freezed:
  json_serializable: